import { Space_Grotesk, Tilt_Neon } from "next/font/google";
import "../node_modules/bootstrap/dist/css/bootstrap.min.css";
import "./Styles/base/common.css";
import "./Styles/components/sections.css";

const tilt_neon = Tilt_Neon({
    subsets: ["latin"],
    variable: "--font-tilt-neon",
});
const space_grotesk = Space_Grotesk({
    weight: "600",
    subsets: ["latin"],
    variable: "--font-space-grotesk",
});

export const metadata = {
    title: "Judah Oyedele's Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${tilt_neon.variable} ${space_grotesk.variable}`}>
                {children}
            </body>
        </html>
    );
}
